apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-clone-app
  labels:
    app: swiggy-clone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-clone-app
  template:
    metadata:
      labels:
        app: swiggy-clone-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: swiggy-clone-app
        image: abbeydauda/swiggy-clone:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
